export { default as Cerebralpalsy } from "./Cerebralpalsy";
export { default as Home } from "./Home";
export { default as Contact } from "./Contact";
export { default as Aboutus } from "./Aboutus";
export { default as Entertainment } from "./Entertainment";
export { default as Yourstory } from "./Yourstory";
export { default as Activity } from "./Activity";
export { default as Exercises } from "./Exercises";
export { default as Links } from "./Links";
